apiVersion: v1
kind: Service
metadata:
  name: anchore-db
  namespace: "${NAMESPACE_NAME}"
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 --file docker-compose.yaml convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: anchore-db
spec:
  type: ClusterIP
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: anchore-db
