apiVersion: apps/v1
kind: Deployment
metadata:
  name: anchore-catalog
  namespace: "${NAMESPACE_NAME}"
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 --file docker-compose.yaml convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: anchore-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: anchore-catalog
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 --file docker-compose.yaml
          convert
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: anchore-catalog
    spec:
      containers:
      - name: anchore-catalog
        image: ${ANCHORE_IMAGE}:${ANCHORE_VERSION}
        args:
        - anchore-manager
        - service
        - start
        - catalog
        env:
        - name: ANCHORE_ENDPOINT_HOSTNAME
          value: anchore-catalog
        envFrom:
        - configMapRef:
            name: anchore
        - secretRef:
            name: anchore
        ports:
        - containerPort: 8228
