apiVersion: apps/v1
kind: Deployment
metadata:
  name: anchore-api
  namespace: "${NAMESPACE_NAME}"
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 --file docker-compose.yaml convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: anchore-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: anchore-api
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 --file docker-compose.yaml
          convert
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: anchore-api
    spec:
      containers:
      - name: anchore-api
        image: ${ANCHORE_IMAGE}:${ANCHORE_VERSION}
        args:
        - anchore-manager
        - service
        - start
        - apiext
        env:
        - name: ANCHORE_ADMIN_PASSWORD
          value: ${ANCHORE_ADMIN_PASSWORD}
        - name: ANCHORE_DB_HOST
          value: anchore-db
        - name: ANCHORE_DB_PASSWORD
          value: ${ANCHORE_DB_PASSWORD}
        - name: ANCHORE_ENDPOINT_HOSTNAME
          value: anchore-api
        ports:
        - containerPort: 8228
