apiVersion: v1
kind: Service
metadata:
  name: anchore-policy-engine
  namespace: "${NAMESPACE_NAME}"
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 --file docker-compose.yaml convert
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: anchore-policy-engine
spec:
  type: ClusterIP
  ports:
  - name: "8228"
    port: 8228
    targetPort: 8228
  selector:
    io.kompose.service: anchore-policy-engine
