name: ci

on: push

env:
  GROUP: senacor
  COMMIT_SHA: ${{ github.sha }}
  SERVICE_NAME: anchore
  NAMESPACE_NAME: anchore
  ANCHORE_VERSION: "v0.9.4"
  ANCHORE_IMAGE: docker.io/anchore/anchore-engine
  ANCHORE_ADMIN_PASSWORD: ${{ secrets.ANCHORE_ADMIN_PASSWORD }}
  ANCHORE_DB_PASSWORD: ${{ secrets.ANCHORE_DB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: render
        run: deployment/render.sh

      - name: deploy
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.KUBERNETES_CLUSTER_NAME }} \
            --role-arn ${{ secrets.KUBERNETES_CLUSTER_DEPLOY_ROLE }}
          kubectl apply -f rendered/
